# Generated by Django 5.2.7 on 2025-10-26 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='end_time',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='start_time',
            field=models.DateField(),
        ),
    ]
