# Generated by Django 5.2.7 on 2025-10-28 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_alter_order_end_time_alter_order_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='capacity',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='room',
            name='room_type',
            field=models.CharField(default='standart', max_length=256),
        ),
        migrations.AddField(
            model_name='room',
            name='square',
            field=models.IntegerField(default=20),
        ),
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
