# Generated by Django 5.2.7 on 2025-10-28 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0003_room_capacity_room_room_type_room_square_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
