# Generated by Django 5.2.7 on 2025-10-30 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0005_remove_order_customer_order_user_delete_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='description_en',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='description_ru',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='description_uk',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='room_type_en',
            field=models.CharField(default='standart', max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='room_type_ru',
            field=models.CharField(default='standart', max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='room_type_uk',
            field=models.CharField(default='standart', max_length=256, null=True),
        ),
    ]
